spring.application.name=shelflife
spring.jpa.hibernate.ddl-auto=update
spring.config.import=file:.env[.properties]

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB